name: CI

on:
  push:
    branches: [main]
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install mise
        run: curl https://mise.jdx.dev/install.sh | sh

      - name: Setup Node.js using mise
        run: |
          mise install
          mise use node

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile

      - name: Run tests
        run: npm run test:coverage

      - name: Run octocov
        uses: k1LoW/octocov-action@v0

      - name: Build VSIX
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: '*.vsix'
